### ISSUE TITLE
Flash embedded with SWFObject can't be run if plugin is not always enabled

### ISSUE THREAD

**Issue by Hubbitus** [swfobject/swfobject#57]
If on plugin page in Chromium browser I do not set checkbox "Always Allowed" on Flash plugin I could manually activate flash content on sites which embed swf directly. But if they use SWFObject I always see "Alternative content" as per you test page.

It is because [nav.plugins](https://github.com/swfobject/swfobject/blob/master/swfobject/src/swfobject.js#L51) does not have `SHOCKWAVE_FLASH` item.

There should be possibility to check "possibility to enable" and ask user to do so as it happened in direct method.

**Comment by chatziko** [comment]
Recent versions of chrome might pretend that FP is unavailable. I don't think there is a way to reliably detect the "possibility to enable". Since chrome comes with embedded FP most likely it is there and the user "just" has to click to enable.

So if you have no HTML5 alternative, I think the best is to hack swfobject into believing that FP is available:

```
if(window.chrome)
  swfobject.ua.pv = [100, 0, 0];  // we have FP v100, hoorray
swfobject.embedSWF(...);
```

**Comment by Hubbitus** [comment]
I use Chromium and it come without Flash Plugin bundled, it installed separately PPAPI version. It change nothing - SWFObject just show me "alternative content" without any possibility to enable it!

Not sure how It may be detected, but in that [SO question](http://stackoverflow.com/questions/17727766/how-to-check-flash-plugin-is-blocked-in-chrome) suggested reasonable approach - just try to activate it! If you do not get error (plugin enabled always or it disabled, but allowed by user for that page and invocation) - proceed. Otherwise catch the error and only in that case show alternative content instead of try predict it.

**Comment by saschanaz** [comment]
[daisuki.net](http://www.daisuki.net/) currently refuses showing videos on Edge 15 and Chrome 57 (with [Prefer HTML over Flash](https://www.chromium.org/flash-roadmap#TOC-HTML5-By-Default-Target:-Chrome-55---Dec-2016-) enabled) because of this issue. Appending empty SWF might help.

**Comment by lynxerzhang** [comment]
I use @chatziko 's method

1: in return ua's anonymous function
```actionscript3
//for detect chrome, safari and edge
//@see  http://stackoverflow.com/questions/9847580/how-to-detect-safari-chrome-ie-firefox-and-opera-browser
ua = function() {
	//......
	var udaData = {w3: w3cdom, pv: playerVersion, wk: webkit, ie: ie, win: windows, mac: mac};
	var isChrome = !!win.chrome && !!win.chrome.webstore;
	var isSafari = /constructor/i.test(window.HTMLElement) || 
	(function (p) { return p.toString() === "[object SafariRemoteNotification]"; })(!window['safari'] || safari.pushNotification);
	var isIE = /*@cc_on!@*/false || !!document.documentMode;
	var isEdge = !isIE && !!window.StyleMedia;
	if(isChrome || isSafari || isEdge){
		udaData.pv[0] = 100;
	}
	return udaData;
}(),
```

2: in testPlayerVersion function
```actionscript3
if (typeof t.GetVariable != UNDEF) {
	try{
		var d = t.GetVariable("$version");
		if (d) {
			d = d.split(" ")[1].split(",");
			ua.pv = [parseInt(d[0], 10), parseInt(d[1], 10), parseInt(d[2], 10)];
		}
	}
	catch (e) {
		var isChrome = !!win.chrome && !!win.chrome.webstore;
		var isSafari = /constructor/i.test(window.HTMLElement) || 
		(function (p) { return p.toString() === "[object SafariRemoteNotification]"; })(!window['safari'] || safari.pushNotification);
		var isIE = /*@cc_on!@*/false || !!document.documentMode;
		var isEdge = !isIE && !!window.StyleMedia;
		if(isChrome || isSafari || isEdge){
			ua.pv = [100, 0, 0];
		}
		else {
			ua.pv = [8, 0, 0];
		}
	}
}
```
and that could work

**Comment by ROBERT-MCDOWELL** [comment]
So maybe make a push commit to solve this issue?

**Comment by saschanaz** [comment]
No one maintains this anymore.

>the authors of SWFObject have moved on to other projects

The pain is there still are some websites that still depend on this... If you are users that crying because of the problem then check out [my user script](https://gist.github.com/SaschaNaz/8bbe4f5270c9cf15acec7ba8b517094a), else please throw Flash away completely on your websites.

**Comment by ROBERT-MCDOWELL** [comment]
well, look at the forks 484 are waiting your commit.
and, frankly, no one will force me to replace a good technology to a crappy slow javascript / hml5. it's like compare an apple to an orange. there are plenty of features not available on html5 and will probably never like multicast etc...
flash is still and will be for long time the right technology for RIA on the web, that's why chrome and other upgrade flash player as PPAPI.
developers and users are so control minded with what it is said about the web technology that no one will profit from it if they don't follow their own interest and benefit.
Open source is based on contributors, so go ahead, don't be shy or too rude

**Comment by saschanaz** [comment]
@madovsky Not removing Flash will make the experience of your websites worse, please take a look on Chromium's roadmap to deprecate Flash: https://www.chromium.org/flash-roadmap

In short, by October 2017 Chrome will force click-to-play on all websites using Flash.

**Comment by saschanaz** [comment]
BTW it seems there already is a good PR :smile: https://github.com/swfobject/swfobject/pull/59

**Comment by ROBERT-MCDOWELL** [comment]
again, you still believe to a monolithic communist web world.
it's not black and white since 1997, it's always up to you to change this behavior
try to understand that websites using flash is not for only for simple animations or play a video,
it's many kind of RIA used by companies, businesses, artists and so who will take ages and big money  to convert actionscript 3 in a crappy javascript stupid way that for sure won't work better.
it's all a question of monopoly, hmtl5 guys are not angels, flash player guys are not deamons, but for sure, at the end everyone wants to be the king. 
Developers and users need only one thing, respect and the best technology to develop and use.
and for now actionscript is for me the best far away from the rest.

**Comment by ROBERT-MCDOWELL** [comment]
fork swobject and continue your own, thousands of users will follow you.

**Comment by ROBERT-MCDOWELL** [comment]
I forked mine and for sure share patches will continue to make users and developers happy.

**Comment by ROBERT-MCDOWELL** [comment]
or if you don't want to patch your own fork so patch mine ;)
